language: clojure
sudo: false
addons:
  apt:
    packages:
      - protobuf-compiler
      - libprotoc-dev
script: lein build-test
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk6
  - openjdk7
notifications:
  email:
    - oubiwann@gmail.com

