language: clojure
sudo: false
before_install:
  - export PATH=$HOME/protobuf/bin:$PATH
  - export C_INCLUDE_PATH=$C_INCLUDE_PATH:$HOME/protobuf/include
  - export CPLUS_INCLUDE_PATH=$CPLUS_INCLUDE_PATH:$HOME/protobuf/include
install:
  - mkdir -p $HOME/protobuf && pushd $HOME/protobuf &&
    curl -LO 'https://github.com/google/protobuf/releases/download/v3.6.0/protoc-3.6.0-linux-x86_64.zip' &&
    unzip protoc-3.6.0-linux-x86_64.zip &&
    popd
script: lein build-test
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk6
  - openjdk7
notifications:
  email:
    - oubiwann@gmail.com

